package de.lenneflow.workerservice.util;

import de.lenneflow.workerservice.dto.ManagedClusterDTO;
import de.lenneflow.workerservice.dto.UnmanagedClusterDTO;
import de.lenneflow.workerservice.exception.InternalServiceException;
import de.lenneflow.workerservice.exception.PayloadNotValidException;
import de.lenneflow.workerservice.model.KubernetesCluster;
import de.lenneflow.workerservice.repository.ApiCredentialRepository;
import de.lenneflow.workerservice.repository.KubernetesClusterRepository;
import org.springframework.stereotype.Component;

@Component
public class PayloadValidator {

    final KubernetesClusterRepository kubernetesClusterRepository;
    final ApiCredentialRepository apiCredentialRepository;


    public PayloadValidator(KubernetesClusterRepository kubernetesClusterRepository, ApiCredentialRepository apiCredentialRepository) {
        this.kubernetesClusterRepository = kubernetesClusterRepository;
        this.apiCredentialRepository = apiCredentialRepository;
    }


    public void validate(KubernetesCluster kubernetesCluster) {
        if(kubernetesCluster.getUid() == null || kubernetesCluster.getUid().isEmpty()) {
            throw new InternalServiceException("Uuid was not generated by the system");
        }

    }

    public void validate(ManagedClusterDTO managedClusterDTO) {

        if(managedClusterDTO.getClusterName() == null || managedClusterDTO.getClusterName().isEmpty()) {
            throw new PayloadNotValidException("KubernetesCluster Name is required");
        }
        if(managedClusterDTO.getRegion() == null || managedClusterDTO.getRegion().isEmpty()) {
            throw new PayloadNotValidException("Region is required");
        }

        if(managedClusterDTO.getCloudProvider() == null || managedClusterDTO.getCloudProvider().toString().isEmpty()) {
            throw new PayloadNotValidException("CloudProvider is required");
        }

        if(managedClusterDTO.getSupportedFunctionTypes() == null || managedClusterDTO.getSupportedFunctionTypes().isEmpty()) {
            throw new PayloadNotValidException("SupportedFunctionTypes is required");
        }
        if(managedClusterDTO.isCreate()){
            if(managedClusterDTO.getSecurityGroupId() == null || managedClusterDTO.getSecurityGroupId().isEmpty()) {
                throw new PayloadNotValidException("Security Group Id is required");
            }
            if(managedClusterDTO.getSubnetIds() == null || managedClusterDTO.getSubnetIds().isEmpty()) {
                throw new PayloadNotValidException("Subnet Ids are required");
            }
            if(managedClusterDTO.getRoleArn() == null || managedClusterDTO.getRoleArn().isEmpty()) {
                throw new PayloadNotValidException("Role Arn is required");
            }
        }


    }

    public void validate(UnmanagedClusterDTO unmanagedClusterDTO) {
        if(unmanagedClusterDTO.getClusterName() == null || unmanagedClusterDTO.getClusterName().isEmpty()) {
            throw new PayloadNotValidException("KubernetesCluster Name is required");
        }
        if(unmanagedClusterDTO.getHostName() == null || unmanagedClusterDTO.getHostName().isEmpty()) {
            throw new PayloadNotValidException("HostName is required");
        }
        if(unmanagedClusterDTO.getApiServerEndpoint() == null || unmanagedClusterDTO.getApiServerEndpoint().isEmpty()) {
            throw new PayloadNotValidException("ApiServerEndpoint is required");
        }
        if(unmanagedClusterDTO.getApiAuthToken() == null || unmanagedClusterDTO.getApiAuthToken().isEmpty()) {
            throw new PayloadNotValidException("ApiAuthToken is required");
        }
        if(unmanagedClusterDTO.getSupportedFunctionTypes() == null || unmanagedClusterDTO.getSupportedFunctionTypes().isEmpty()) {
            throw new PayloadNotValidException("SupportedFunctionTypes is required");
        }
    }
}
