apiVersion: v1
kind: Service
metadata:
  name: function-service
  labels:
    app: function-service
    spring-boot: "true"
spec:
  ports:
    - port: 47003
      protocol: TCP
  selector:
    app: function-service
  type: ClusterIP