kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-service
data:
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  application.yml: |-
    spring:
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: account-service
              uri: account-service
              predicates:
                - Path=/account/**
              filters:
                - RewritePath=/account/(?<path>.*), /$\{path}
            - id: execution-service
              uri: execution-service
              predicates:
                - Path=/execution/**
              filters:
                - RewritePath=/execution/(?<path>.*), /$\{path}
            - id: task-service
              uri: task-service
              predicates:
                - Path=/task/**
              filters:
                - RewritePath=/task/(?<path>.*), /$\{path}
            - id: worker-service
              uri: worker-service
              predicates:
                - Path=/worker/**
              filters:
                - RewritePath=/worker/(?<path>.*), /$\{path}
            - id: workflow-service
              uri: http://leneflow.local/workflow-service
              predicates:
                - Path=/workflow/**
              filters:
                - RewritePath=/workflow/(?<path>.*), /$\{path}