apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      serviceAccountName: lenneflow-sa
      containers:
      - name: gateway
        image: lenneflow/gateway-service
        ports:
        - containerPort: 8080