kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-service
data:
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  application.properties: |-
    spring.cloud.gateway.routes[0].id=account-service
    spring.cloud.gateway.routes[0].filters=RewritePath=/account/(?<path>.*), /$\{path}
    spring.cloud.gateway.routes[0].predicates[0]=Path=/account/**
    spring.cloud.gateway.routes[2].id=execution-service
    spring.cloud.gateway.routes[2].filters=RewritePath=/orchestration/(?<path>.*), /$\{path}
    spring.cloud.gateway.routes[2].predicates[2]=Path=/orchestration/**
    spring.cloud.gateway.routes[3].id=task-service
    spring.cloud.gateway.routes[3].filters=RewritePath=/task/(?<path>.*), /$\{path}
    spring.cloud.gateway.routes[3].predicates[3]=Path=/task/**
    spring.cloud.gateway.routes[1].id=worker-service
    spring.cloud.gateway.routes[1].filters=RewritePath=/worker/(?<path>.*), /$\{path}
    spring.cloud.gateway.routes[1].predicates[1]=Path=/worker/**
    spring.cloud.gateway.routes[4].id=workflow-service
    spring.cloud.gateway.routes[4].filters=RewritePath=/workflow/(?<path>.*), /$\{path}
    spring.cloud.gateway.routes[4].predicates[4]=Path=/workflow/**