apiVersion: v1
kind: Service
metadata:
  name: orchestration-service
  labels:
    app: orchestration-service
    spring-boot: "true"
spec:
  ports:
    - port: 47002
      protocol: TCP
  selector:
    app: orchestration-service
  type: ClusterIP