apiVersion: v1
kind: ServiceAccount
metadata:
  name: lenneflow-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lenneflow-sa
  namespace: lenneflow
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lenneflow-sa
  namespace: lenneflow
subjects:
  - kind: ServiceAccount
    name: lenneflow-sa
    namespace: lenneflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lenneflow-sa