apiVersion: v1
kind: Service
metadata:
  name: task-service
  labels:
    app: task-service
    spring-boot: "true"
spec:
  ports:
    - port: 47003
      protocol: TCP
  selector:
    app: task-service
  type: ClusterIP