kind: ConfigMap
apiVersion: v1
metadata:
  name: task-service
data:
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  application.properties: |-
    spring.data.mongodb.host=mongodb
    spring.data.mongodb.database:admin
    spring.data.mongodb.authentication-database:admin