apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service
  labels:
    app: workflow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-service
  template:
    metadata:
      labels:
        app: workflow-service
    spec:
      serviceAccountName: lenneflow-sa
      hostNetwork: true
      containers:
      - name: workflow-service
        image: lenneflow/workflow-service
        ports:
        - containerPort: 47005
          hostPort: 47005
        resources:
          requests:
            cpu: "0.2"
            memory: 300Mi
          limits:
            cpu: "1.0"
            memory: 300Mi
        readinessProbe:
            httpGet:
              port: 47005
              path: /actuator/health
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
        livenessProbe:
            httpGet:
              port: 47005
              path: /actuator/info
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
        volumeMounts:
            - name: mongodb
              mountPath: /etc/secretspot
          #            - name: config
          #              mountPath: /etc/appconfig
        env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"
          #          - name: SPRING_CONFIG_IMPORT
          #            value: "kubernetes:"
      volumes:
            - name: mongodb
              secret:
                secretName: workflow-service
          #        - name: config
          #          configMap:
          #            name: department