apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker-service
    spring-boot: "true"
spec:
  ports:
    - port: 47004
      protocol: TCP
  selector:
    app: worker-service
  type: ClusterIP