apiVersion: v1
kind: Service
metadata:
  name: execution-service
  labels:
    app: execution-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: execution-service
  type: ClusterIP