apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: task-service
        image: lenneflow/task-service
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
            value: "true"
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
            value: "true"
#          - name: SPRING_CONFIG_IMPORT
#            value: "kubernetes:"